export const COUNTRIES = [
  "India",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Singapore",
  "United Arab Emirates",
  "Japan",
  "Brazil",
  "South Africa",
  "New Zealand",
  "Netherlands",
  "Ireland",
  "Other",
];
